"""Add sentry opt in/out for user

Revision ID: 85a5f3352965
Revises: 4b26a54d861d
Create Date: 2024-03-10 21:38:46.228935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "85a5f3352965"
down_revision: Union[str, None] = "4b26a54d861d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("sentry_enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "sentry_enabled")
    # ### end Alembic commands ###
