"""Remove ConvesationMessage Association table

Revision ID: 1ee503ad6653
Revises: a5798b58740f
Create Date: 2024-03-26 16:05:14.798991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ee503ad6653"
down_revision: Union[str, None] = "a5798b58740f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_messages")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("conversation_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_messages_conversation_id_conversations"),
            "conversations",
            ["conversation_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_messages_conversation_id_conversations"), type_="foreignkey")
        batch_op.drop_column("conversation_id")

    op.create_table(
        "conversation_messages",
        sa.Column("message_id", sa.INTEGER(), nullable=False),
        sa.Column("conversation_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="fk_conversation_messages_conversation_id_conversations",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name="fk_conversation_messages_message_id_messages", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("message_id", "conversation_id"),
    )
    # ### end Alembic commands ###
