"""Cascade FK deletions

Revision ID: a5798b58740f
Revises: 4b26a54d861d
Create Date: 2024-03-26 14:00:51.129953

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a5798b58740f"
down_revision: Union[str, None] = "4b26a54d861d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connections", schema=None, naming_convention=naming_convention) as batch_op:
        # Give the constraint a name
        batch_op.drop_constraint("uq_connections_dsn", type_="unique")
        batch_op.create_unique_constraint(batch_op.f("uq_connections_dsn"), ["dsn"])

    with op.batch_alter_table("conversation_messages", schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_conversation_messages_conversation_id_conversations", type_="foreignkey")
        batch_op.drop_constraint("fk_conversation_messages_message_id_messages", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_conversation_messages_conversation_id_conversations"),
            "conversations",
            ["conversation_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_conversation_messages_message_id_messages"),
            "messages",
            ["message_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("conversations", schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_conversations_connection_id_connections", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_conversations_connection_id_connections"),
            "connections",
            ["connection_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("message_results", schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_message_results_message_id_messages", type_="foreignkey")
        batch_op.drop_constraint("fk_message_results_result_id_results", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_message_results_message_id_messages"), "messages", ["message_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_message_results_result_id_results"), "results", ["result_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("saved_queries", schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_saved_queries_result_id_results", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_saved_queries_result_id_results"), "results", ["result_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("schema_fields", schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_schema_fields_table_id_schema_tables", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_schema_fields_table_id_schema_tables"),
            "schema_tables",
            ["table_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("schema_tables", schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_schema_tables_connection_id_connections", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_schema_tables_connection_id_connections"),
            "connections",
            ["connection_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schema_tables", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_schema_tables_connection_id_connections"), type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_schema_tables_connection_id_connections", "connections", ["connection_id"], ["id"]
        )

    with op.batch_alter_table("schema_fields", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_schema_fields_table_id_schema_tables"), type_="foreignkey")
        batch_op.create_foreign_key("fk_schema_fields_table_id_schema_tables", "schema_tables", ["table_id"], ["id"])

    with op.batch_alter_table("saved_queries", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_saved_queries_result_id_results"), type_="foreignkey")
        batch_op.create_foreign_key("fk_saved_queries_result_id_results", "results", ["result_id"], ["id"])

    with op.batch_alter_table("message_results", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_message_results_result_id_results"), type_="foreignkey")
        batch_op.drop_constraint(batch_op.f("fk_message_results_message_id_messages"), type_="foreignkey")
        batch_op.create_foreign_key("fk_message_results_message_id_messages", "messages", ["message_id"], ["id"])
        batch_op.create_foreign_key("fk_message_results_result_id_results", "results", ["result_id"], ["id"])

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_conversations_connection_id_connections"), type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_conversations_connection_id_connections", "connections", ["connection_id"], ["id"]
        )

    with op.batch_alter_table("conversation_messages", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_conversation_messages_message_id_messages"), type_="foreignkey")
        batch_op.drop_constraint(
            batch_op.f("fk_conversation_messages_conversation_id_conversations"), type_="foreignkey"
        )
        batch_op.create_foreign_key("fk_conversation_messages_message_id_messages", "messages", ["message_id"], ["id"])
        batch_op.create_foreign_key(
            "fk_conversation_messages_conversation_id_conversations", "conversations", ["conversation_id"], ["id"]
        )

    # ### end Alembic commands ###
