"""Add preferred openai model field

Revision ID: ffda068eb4b2
Revises: 32035ba6ade3
Create Date: 2024-04-01 22:21:50.205103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffda068eb4b2"
down_revision: Union[str, None] = "32035ba6ade3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("preferred_openai_model", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("preferred_openai_model")

    # ### end Alembic commands ###
