"""Add sentry opt in/out for user

Revision ID: 99075557ba6e
Revises: 6a78ebe5b53e
Create Date: 2024-05-28 10:34:19.765968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99075557ba6e"
down_revision: Union[str, None] = "6a78ebe5b53e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sentry_enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("sentry_enabled")

    # ### end Alembic commands ###
