"""add langsmith api key to user details

Revision ID: 9425e09b2c83
Revises: 6a78ebe5b53e
Create Date: 2024-05-27 20:00:40.421725

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9425e09b2c83"
down_revision: Union[str, None] = "6a78ebe5b53e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saved_queries")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("langsmith_api_key", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("langsmith_api_key")

    op.create_table(
        "saved_queries",
        sa.Column("result_id", sa.CHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_id"], ["results.id"], name="fk_saved_queries_result_id_results", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("result_id", name="pk_saved_queries"),
    )
    # ### end Alembic commands ###
