"""Update conversation created_at

Revision ID: 47fc8627a7d1
Revises: ffda068eb4b2
Create Date: 2024-05-09 20:30:59.628114

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47fc8627a7d1"
down_revision: Union[str, None] = "ffda068eb4b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column("created_at", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###
