"""Remove SavedQuery table

Revision ID: 4d3e13d7f6d1
Revises: c8c61fb4633d
Create Date: 2024-05-21 11:48:19.614577

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d3e13d7f6d1"
down_revision: Union[str, None] = "c8c61fb4633d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saved_queries")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_queries",
        sa.Column("result_id", sa.CHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_id"], ["results.id"], name="fk_saved_queries_result_id_results", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("result_id", name="pk_saved_queries"),
    )
    # ### end Alembic commands ###
