"""refactor models

Revision ID: 0bb61e12b792
Revises: 47fc8627a7d1
Create Date: 2024-05-14 21:01:13.577194

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from dataline.models.base import CustomUUIDType

# revision identifiers, used by Alembic.
revision: str = "0bb61e12b792"
down_revision: Union[str, None] = "47fc8627a7d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schema_tables")
    op.drop_table("schema_fields")
    op.drop_table("message_results")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=sa.INTEGER(), type_=CustomUUIDType(), existing_nullable=False)

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.alter_column(
            "conversation_id",
            existing_type=sa.INTEGER(),
            type_=CustomUUIDType(),
            existing_nullable=False,
        )
        batch_op.alter_column("id", existing_type=sa.INTEGER(), type_=CustomUUIDType(), existing_nullable=False)
        batch_op.drop_column("selected_tables")

    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.add_column(sa.Column("message_id", CustomUUIDType(), nullable=False))
        batch_op.alter_column("id", existing_type=sa.INTEGER(), type_=CustomUUIDType(), existing_nullable=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_results_message_id_messages"), "messages", ["message_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("saved_queries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", CustomUUIDType(), nullable=False))
        batch_op.alter_column(
            "result_id",
            existing_type=sa.INTEGER(),
            type_=CustomUUIDType(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("saved_queries", schema=None) as batch_op:
        batch_op.alter_column(
            "result_id",
            existing_type=CustomUUIDType(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )
        batch_op.drop_column("id")

    with op.batch_alter_table("results", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_results_message_id_messages"), type_="foreignkey")
        batch_op.alter_column("id", existing_type=CustomUUIDType(), type_=sa.INTEGER(), existing_nullable=False)
        batch_op.drop_column("message_id")

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("selected_tables", sa.VARCHAR(), nullable=False))
        batch_op.alter_column("id", existing_type=CustomUUIDType(), type_=sa.INTEGER(), existing_nullable=False)
        batch_op.alter_column(
            "conversation_id",
            existing_type=CustomUUIDType(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column("id", existing_type=CustomUUIDType(), type_=sa.INTEGER(), existing_nullable=False)

    op.create_table(
        "message_results",
        sa.Column("message_id", sa.INTEGER(), nullable=False),
        sa.Column("result_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name="fk_message_results_message_id_messages", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["result_id"], ["results.id"], name="fk_message_results_result_id_results", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("message_id", "result_id", name="pk_message_results"),
    )
    op.create_table(
        "schema_fields",
        sa.Column("table_id", sa.CHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("type", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("is_primary_key", sa.BOOLEAN(), nullable=False),
        sa.Column("is_foreign_key", sa.BOOLEAN(), nullable=False),
        sa.Column("foreign_table", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["table_id"], ["schema_tables.id"], name="fk_schema_fields_table_id_schema_tables", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_schema_fields"),
    )
    op.create_table(
        "schema_tables",
        sa.Column("connection_id", sa.CHAR(length=32), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"], ["connections.id"], name="fk_schema_tables_connection_id_connections", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_schema_tables"),
    )
    # ### end Alembic commands ###
