class RelatedTablesNotFoundError(Exception): ...


class GenerationError(Exception): ...


class NotFoundError(Exception): ...


class UpdateError(Exception): ...


class InsertError(Exception): ...


class ValidationError(ValueError): ...


# error that we can communicate to the user
class UserFacingError(Exception): ...
